# .github/workflows/main.yml

name: AutoDevOps PR Review Pipeline

# --- 1. Define when this workflow runs ---
on:
  pull_request:
    types: [opened, synchronize, reopened] # Runs when a PR is created or updated

# --- 2. Define the main job ---
jobs:
  run_auto_review:
    runs-on: ubuntu-latest
    
    # CRITICAL: Grant pull-requests: write permission
    permissions:
      contents: read
      pull-requests: write # This is what allows the bot to post the comment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # --- NEW STEP ADDED HERE ---
      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          # This is the path where pip stores its downloaded packages
          path: ~/.cache/pip
          # This creates a unique key for the cache based on the runner's OS 
          # and a HASH (a unique ID) of your requirements.txt file.
          # If requirements.txt changes, the hash changes, and the cache is rebuilt.
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      # --- END OF NEW STEP ---

      - name: Install Dependencies
        run: |
          # Install all project dependencies
          python -m pip install --upgrade pip
          # This command will now run much faster on subsequent runs
          pip install -r requirements.txt
          pip install "crewai[google-genai]"
          
      - name: Execute 5-Agent Pipeline
        # This step passes the environment variables to the Python script
        run: python agent_reviewer.py
        env:
          # Passes the Gemini secret
          GOOGLE_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          
          # FIX: We use the built-in GITHUB_TOKEN and pass it as GITHUB_PAT.
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} 
          
          # Pass the current PR URL
          PR_URL: ${{ github.event.pull_request.html_url }}