# .github/workflows/main.yml

name: AutoDevOps PR Review Pipeline

# --- Triggers the workflow on every Pull Request update ---
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run_auto_review:
    runs-on: ubuntu-latest
    
    # CRITICAL: Grant pull-requests: write permission to the GITHUB_TOKEN
    permissions:
      contents: read
      pull-requests: write 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          # Install core dependencies (crewai, pytest, PyGithub, etc.)
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "crewai[google-genai]"
          
      - name: Execute 5-Agent Pipeline
        # This step runs your final, corrected Python script
        run: python agent_reviewer.py
        env:
          # Passes the Gemini secret
          GOOGLE_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          
          # CRITICAL FIX: Use the built-in GITHUB_TOKEN. Your Python script 
          # must be coded to read this as GITHUB_PAT (or GITHUB_TOKEN).
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} 
          
          # Pass the current PR URL
          PR_URL: ${{ github.event.pull_request.html_url }}