# .github/workflows/main.yml

name: AutoDevOps PR Review Pipeline

# --- 1. Define when this workflow runs ---
on:
  pull_request:
    types: [opened, synchronize, reopened]

# --- 2. Define the main job ---
jobs:
  run_auto_review:
    runs-on: ubuntu-latest
    
    # CRITICAL: Grant full permissions for reading and writing comments/checks
    permissions:
      contents: read
      pull-requests: write 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "crewai[google-genai]"
          
      - name: Execute 4-Agent Pipeline
        run: python agent_reviewer.py
        env:
          # Passes the stored Gemini secret securely
          GOOGLE_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          
          # CRITICAL FIX: Use the built-in token provided by GitHub Actions
          # This token is always available and has the 'pull-requests: write' permission.
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} 
          
          # Pass the current PR URL
          PR_URL: ${{ github.event.pull_request.html_url }}
